### ISSUE TITLE
Reverb uses too much CPU (mikmod md_reverb)

### ISSUE THREAD

**Issue by mills32** [dogo/oslibmodv2#13]
This is not really an issue, just a suggestion.

You should add a function to change mikmod reverb (md_reverb in MDRIVER.C), because actual value of 6, uses a lot of CPU. Even a 0 value is ok and uses way less CPU.

Thanks!.

**Comment by dogo** [comment]
Hi @mills32 , I'm removing the local and outdated MikMod library with the version from PSPSDK. The current implementation poses compatibility issues and lacks necessary updates. By integrating the PSPSDK version, we ensure better support for modern platforms and improved functionality, aligning our project with current development standards. This update not only streamlines our codebase but also sets a foundation for future enhancements and smoother integration with third-party tools.

https://github.com/dogo/oslibmodv2/pull/14
