### ISSUE TITLE
OSL Fonts are being created as an empty file

### ISSUE THREAD

**Issue by HeroEpic** [dogo/oslibmodv2#23]
I converted a truetype font and it worked, but when I go to the part to create the OSL font, the file is created as an empty file. If possible, tell me a procedure using Linux so I can try to convert.
Sorry for the bad english!

**Comment by dogo** [comment]
Here's the translation:

Hello, @HeroEpic , to be able to help, I need you to open the issue correctly. When creating an issue, there is information to be filled out to provide more details about the environment and the steps to reproduce the problem. If you could also attach an example, that would be very helpful.

**Comment by HeroEpic** [comment]
I tested it on another computer and it worked. Thanks!
